import 'package:flutter/material.dart';
import 'package:password_generator/screen/authentication_text.dart';

class PasswordList extends StatefulWidget {
  const PasswordList({Key? key});

  @override
  State<PasswordList> createState() => _PasswordListState();
}

class _PasswordListState extends State<PasswordList> {
  late Widget password2 = password;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(
          'Add New Password',
          style: TextStyle(fontWeight: FontWeight.w800),
        ),
      ),
      body: Form(
        child: ListView(
          children: [
            Padding(
              padding: const EdgeInsets.all(16.0),
              child: Column(
                children: [
                  SizedBox(
                    height: 25,
                  ),
                  TextFormField(
                    decoration: InputDecoration(
                      labelText: 'App or Site Name',
                      hintText: 'App or Site Name',
                      border: OutlineInputBorder(),
                      helperText:
                          'The Site/App which you are going to store the password',
                    ),
                    validator: (value) {
                      if (value == null || value.isEmpty) {
                        return 'Please enter app or site name';
                      }
                      return null;
                    },
                  ),
                  SizedBox(
                    height: 15,
                  ),
                  TextFormField(
                    decoration: InputDecoration(
                      labelText: 'Username',
                      prefixIcon: Icon(Icons.person),
                      hintText: 'Username',
                      border: OutlineInputBorder(),
                      helperText:
                          'Enter The Username/Id Which you use in that app',
                    ),
                    validator: (value) {
                      if (value == null || value.isEmpty) {
                        return 'Please enter username';
                      }
                      return null;
                    },
                  ),
                  SizedBox(height: 25),
                  Container(
                    child: Row(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: [
                        ElevatedButton(
                          onPressed: () {
                            setState(() {
                              password2 = password;
                            });
                          },
                          child: Text('I Have a password'),
                        ),
                        SizedBox(
                          width: 25,
                        ),
                        ElevatedButton(
                          onPressed: () {
                            setState(() {
                              password2 = Column(
                                children: [
                                  TextFormField(
                                    decoration: InputDecoration(
                                        labelText: 'hint',
                                        helperText: 'Enter A Hint',
                                        prefixIcon: Icon(Icons.lightbulb),
                                        border: OutlineInputBorder()),
                                    validator: (value) {
                                      if (value == null || value.isEmpty) {
                                        return 'Please enter hint';
                                      }
                                      return null;
                                    },
                                  ),
                                  SizedBox(
                                    height: 20,
                                  ),
                                  TextFormField(
                                    decoration: InputDecoration(
                                        labelText: 'Autogenerated Password',
                                        helperText:
                                            'Just Save The Current Password',
                                        prefixIcon: Icon(Icons.lock),
                                        border: OutlineInputBorder()),
                                    validator: (value) {
                                      if (value == null || value.isEmpty) {
                                        return 'Please enter password';
                                      }
                                      return null;
                                    },
                                  ),
                                ],
                              );
                            });
                          },
                          child: Text('Autogenerate'),
                        ),
                      ],
                    ),
                  ),
                  SizedBox(
                    height: 25,
                  ),
                  FormField(
                    builder: (state) {
                      return password2;
                    },
                    validator: (value) {
                      // You can implement form validation logic here
                      return null;
                    },
                  ),
                  SizedBox(height: 25),
                  ElevatedButton(
                      onPressed: () {}, child: Text('Add New PassWord'))
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
}
